name: Testing

on:
  push:
  pull_request:
  schedule:
    # run tests on every week Monday
    - cron: '0 0 * * 1'

jobs:
  static_analysis:
    name: Static Analysis

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: xdebug

      - name: Get composer cache directory
        run: echo "COMPOSER_DIR=$(composer config cache-files-dir)" >> $GITHUB_ENV

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.COMPOSER_DIR }}
          key: ${{ runner.os }}-composer-static-analysis-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-static-analysis-

      - name: Install dependencies
        run: composer update --no-progress --no-interaction

      - name: Check runtime dependencies
        run: composer check-platform-reqs

      - name: Run composer validate
        run: composer validate --strict

      - name: Run composer normalize
        run: composer normalize --dry-run

      - name: Run static analysis
        run: vendor/bin/phpstan --memory-limit=-1 --verbose

      - name: Run coding style checker
        run: vendor/bin/pint -v --test

  testing:
    name: Laravel ${{ matrix.laravel }}, PHP ${{ matrix.php }}, OS ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        laravel: [ '10', '9', '8' ]
        php: [ '8.2', '8.1', '8.0' ]
        os: [ ubuntu-latest, windows-latest, macOS-latest ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: fileinfo, imagick
          coverage: xdebug

      - name: Get composer cache directory for Windows
        if: runner.os == 'Windows'
        run: echo "COMPOSER_DIR=$(composer config cache-files-dir)" >> $env:GITHUB_ENV

      - name: Get composer cache directory for other OS
        if: runner.os != 'Windows'
        run: echo "COMPOSER_DIR=$(composer config cache-files-dir)" >> $GITHUB_ENV

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.COMPOSER_DIR }}
          key: ${{ runner.os }}-composer-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-laravel-

      - name: Install dependencies
        run: composer update --with illuminate/support:~${{ matrix.laravel }} --no-progress --no-interaction

      - name: Run tests
        run: vendor/bin/phpunit
